# Hypothesis Testing
Proposed Explanation

1. Null Hypothesis H0: It is considered true till it proven false.
2. Alternative Hypothesis: It is the negation of the null hypothesis.


Select a test: and apply it -> test statistics

we need to convert this test statistics to a p-value

#### significance level
threshold for luck -> 5%

p-value < 0.05 -> we will reject the null hypothesis and accept the alternative hypothesis.

#### a large p-value indicates that the results are due to luck.

In [2]:
# Lady tasting Tea

#is it possible for you to tell weather the tea added before or after the milk?

H0: the lady cannot tell if the milk was poured first.
                (NH possess no relationship and no difference)
H1: the lady can tell if the milk was poured first.

#### select a test

8 cups of tea, 4 of each type

Lady got all 8 correct -> test statistics

8C4 -> 70 is the number of combinations

p-value = 1/70 = 1.4%

1.4% < 5% => Reject the H0


### Errors in Hypothesis Testing

Type I error
When you reject the null hypothesis when it was actually true.

Type II error
When we don't reject the null hypothesis and accept the alternative hypothesis.


### Power (Recall)
power of statistical test

probability of rejecting H0 when H1 is true.

If the value of power is high than it is good.

if it is high that means the low probability of Type-II error


### alpha

alpha is the probability of rejecting H0 when H0 is true.

alpha = probability of commiting a Type-I error.

if the test has high alpha value that is not good.

# Chi-Square Test

In [6]:
import scipy.stats as stats

In [7]:
import seaborn as sns
import pandas as pd
import numpy as np

In [8]:
dataset = sns.load_dataset('tips')

dataset.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [9]:
dataset_table = pd.crosstab(dataset['sex'], dataset['smoker'])

print(dataset_table)

smoker  Yes  No
sex            
Male     60  97
Female   33  54


In [13]:
observed_values = dataset_table.values
observed_values

array([[60, 97],
       [33, 54]], dtype=int64)

In [11]:
val = stats.chi2_contingency(dataset_table)

val

(0.0,
 1.0,
 1,
 array([[59.84016393, 97.15983607],
        [33.15983607, 53.84016393]]))

In [12]:
expected_values = val[3]

In [14]:
from scipy.stats import chi2

chi_square = sum([(o-e)**2./e for o, e in  zip(observed_values, expected_values)])

chi_square_stats = chi_square[0] + chi_square[1]

In [15]:
chi_square_stats

0.001934818536627623

In [17]:
no_of_rows = len(dataset_table.iloc[0:2,0])
no_of_columns = len(dataset_table.iloc[0,0:2])
ddof = (no_of_rows - 1) * (no_of_columns - 1)

print("Degree of Freedom:",ddof)

Degree of Freedom: 1


In [19]:
alpha = 0.05

In [20]:
critical_value = chi2.ppf(q=1-alpha, df=ddof)

print("Critical Value:", critical_value)

Critical Value: 3.841458820694124


In [21]:
# p-value

p_value = 1 - chi2.cdf(x=chi_square_stats, df=ddof)

print("p-value:", p_value)
print("Significance Level:", alpha)
print("Degree of Freedom:", ddof)

p-value: 0.964915107315732
Significance Level: 0.05
Degree of Freedom: 1


In [23]:
if chi_square_stats >= critical_value:
    print("Reject H0, there is a relationship between 2 categorical variables")
else:
    print("Accepting H0, there is no relationship between 2 categorical variables")

Accepting H0, there is no relationship between 2 categorical variables


In [24]:
if p_value <= alpha:
    print("Reject H0, there is a relationship between 2 categorical variables")
else:
    print("Accepting H0, there is no relationship between 2 categorical variables")

Accepting H0, there is no relationship between 2 categorical variables


# t-test

if there is a significant difference between the means of two groups

In [25]:
ages = [10,20,35,50,28,40,55,18,16,55,30,25,43,18,30,28,14,24,16,17,32,3,26,27,66,60]

In [26]:
len(ages)

26

In [27]:
ages_mean = np.mean(ages)

In [28]:
ages_mean

30.23076923076923

In [29]:
sample_size = 10

age_sample = np.random.choice(ages, sample_size)

age_sample

array([60, 18, 66, 32, 17, 55, 43, 17, 16, 55])

In [30]:
from scipy.stats import ttest_1samp

ttest, p_value = ttest_1samp(age_sample, 30)

print(p_value)

0.24751746592331406


In [31]:
if p_value < 0.05:
    print("We are rejecting null hypothesis")
else:
    print("We are accepting the Null Hypothesis")

We are accepting the Null Hypothesis
