# NumPy

Numeric Python

In [ ]:
# !pip install numpy

In [1]:
import numpy as np

In [2]:
v = np.array([1,2,3])

print(v)

[1 2 3]


In [3]:
v = np.array([[1],[2],[3]])

print(v)

[[1]
 [2]
 [3]]


In [ ]:
0th dimension ->     .
1 D                  ._____.

2 D                  .___|___.

3 D                  .___|___.
                        /
4 D

## Create a matrix

In [5]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])

print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## selecting elements

In [6]:
v = np.array([1,2,3,4,5,6,7])
#             0 1 2 3
print(v[2])

3


In [7]:
v[:]

array([1, 2, 3, 4, 5, 6, 7])

In [8]:
v[2:5]

array([3, 4, 5])

In [9]:
v[-1]

7

In [10]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])

print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
m = np.array([[1,2,3], [4,5,6], [7,8,9]])

print(m)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
m[0,0]

1

In [13]:
m[1,1]

5

In [14]:
m[:3,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [15]:
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
m[:,1:2]

array([[2],
       [5],
       [8]])

In [17]:
m[1:2,1:2]

array([[5]])

In [18]:
m[1:2,:]

array([[4, 5, 6]])

In [ ]:
00  01  02
10  11  12
20  21  22

## Describe a Matrix

In [25]:
matrix = np.array([[1,2,3,4], [4,5,6,4], [7,8,9,13]])

print(matrix)

[[ 1  2  3  4]
 [ 4  5  6  4]
 [ 7  8  9 13]]


In [26]:
print(matrix.shape)

(3, 4)


In [27]:
print(matrix.size)

12


In [28]:
print(matrix.ndim)

2


## max and min values

In [29]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])

print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [30]:
print(np.max(matrix))

9


In [31]:
print(np.min(matrix))

1


In [32]:
print(np.max(matrix, axis=0)) # column

[7 8 9]


In [33]:
print(np.max(matrix, axis=1)) # row

[3 6 9]


## Mean, Variance and Standard Deviation

In [34]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])

print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [35]:
print(np.mean(matrix))  # 45/9 = 5.0

5.0


In [36]:
print(np.var(matrix))

6.666666666666667


In [37]:
print(np.std(matrix))

2.581988897471611


## Reshaping Array

In [38]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])

print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [39]:
print(matrix.shape)

(3, 3)


In [40]:
print(matrix.reshape(9,1))

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [41]:
print(matrix.reshape(9,2))

ValueError: cannot reshape array of size 9 into shape (9,2)

In [42]:
print(matrix.reshape(9))  # 1 - d array

[1 2 3 4 5 6 7 8 9]


In [43]:
print(matrix.reshape(1,-1))

[[1 2 3 4 5 6 7 8 9]]


In [44]:
print(matrix.flatten())

[1 2 3 4 5 6 7 8 9]


## Transpose of matrix

In [45]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])

print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [46]:
print(matrix.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
720PX
1080px

## Determinant and Rank

In [47]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])

print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [48]:
print(np.linalg.det(matrix))

-9.51619735392994e-16


In [50]:
print(np.linalg.matrix_rank(matrix))  # number of non zero rows

2


# Random Values

In [55]:
print(np.random.randint(0,11,3))

[7 4 8]


In [60]:
np.random.seed(5)

print(np.random.randint(0,11,3))

[3 6 6]


In [62]:
print(np.random.normal(1.0, 2.0, 10))  # normal distribution

[ 2.82374728 -1.88768311  4.64888033  3.91525025 -0.8205163  -0.98003789
 -0.63509625 -1.33655895  0.57844071  0.55140067]


In [ ]:
-1 and 0 and 1